```{r message=FALSE}
nodes <- 
   readr::read_csv(
     system.file("extdata/qtl2shinyNode.csv", package = "qtl2shiny"),
     comment = "#")
edges <- 
   readr::read_csv(
     system.file("extdata/qtl2shinyEdge.csv", package = "qtl2shiny"),
     comment = "#")
```

```{r}
m <- match(edges$source, nodes$node)
edges$source[is.na(m)]
```

```{r}
m <- match(edges$target, nodes$node)
edges$target[is.na(m)]
```

```{r}
table(table(nodes$node))
```

```{r}
nodes$node[which(duplicated(nodes$node))]
```

```{r}
net <- igraph::graph_from_data_frame(d=edges, vertices=nodes, directed=TRUE)
```

```{r}
net <- igraph::simplify(net, remove.multiple = F, remove.loops = TRUE) 
```

```{r}
#change arrow size and edge color:
igraph::E(net)$arrow.size <- .2
igraph::E(net)$edge.color <- "gray80"
```

```{r}
dplyr::count(nodes,logic,shiny)
```

```{r}
dplyr::count(edges,assign)
```

```{r}
net_server <-
  igraph::delete_vertices(
    igraph::delete_edges(
      net,
      igraph::E(net)[!(assign %in% c("server","serverin"))]),
    unclass(igraph::V(net)[logic != "server"]))
```

```{r}
igraph::tkplot(net_server)
```

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=7}
#jpeg("net.jpg", width = 700, height = 700)
plot(net_server, vertex.shape="none", 
     vertex.label=igraph::V(netModule)$node, 
     vertex.label.font=2, vertex.label.color="black",
     vertex.label.cex=1, edge.color="gray50",
     layout = igraph::layout_as_tree)
#invisible(dev.off())
```

```{r}
net_ui <-
  igraph::delete_vertices(
    igraph::delete_edges(
      net,
      igraph::E(net)[assign != "ui"]),
    unclass(igraph::V(net)[logic != "ui"]))
```

```{r}
igraph::tkplot(net_ui)
```

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=7}
plot(net_ui, vertex.shape="none", 
     vertex.label=igraph::V(net_ui)$node, 
     vertex.label.font=2, vertex.label.color="black",
     vertex.label.cex=1, edge.color="gray50",
     layout = igraph::layout_as_tree)
```